euroTrip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('euroTrip/', include('tripRouting.urls')),
    path('admin/', admin.site.urls),
]

tripRouting/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'tripRouting'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('regist/', views.regist, name='regist'),
    path('routing/', views.routing, name='routing'),
    path('routing_ajax_init/', views.routing_ajax_init, name='routing_ajax_init'),
    path('success', views.success, name='success'),
]

tripRouting/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
import json


class City(models.Model):
    city_id = models.IntegerField(primary_key=True)
    city_name = models.CharField(max_length=20)
    city_price = models.IntegerField()
    city_url = models.CharField(max_length=40)
    city_x = models.FloatField()
    city_y = models.FloatField()

    def to_json(self):
        city_dict = {
            'city_id': self.city_id,
            'city_name': self.city_name,
            'city_price': self.city_price,
            'city_url': self.city_url,
            'city_x': self.city_x,
            'city_y': self.city_y,
        }
        return json.dumps(city_dict, ensure_ascii=False).encode('utf-8').decode()

    class Meta:
        managed = False
        db_table = 'city'


class Route(models.Model):
    route_id = models.IntegerField(primary_key=True)
    route_city1 = models.ForeignKey(City, models.DO_NOTHING, db_column='route_city1', related_name='route_city1')
    route_city2 = models.ForeignKey(City, models.DO_NOTHING, db_column='route_city2', related_name='route_city2')
    route_distance = models.IntegerField()
    route_type = models.CharField(max_length=20)
    route_start = models.IntegerField()
    route_finish = models.IntegerField()
    route_fee = models.IntegerField()

    def to_json(self):
        route_dict = {
            'route_id': self.route_id,
            'route_city1': self.route_city1.city_id,
            'route_city2': self.route_city2.city_id,
            'route_distance': self.route_distance,
            'route_type': self.route_type,
            'route_start': self.route_start,
            'route_finish': self.route_finish,
            'route_fee': self.route_fee,
        }
        return json.dumps(route_dict, ensure_ascii=False).encode('utf-8').decode()

    class Meta:
        managed = False
        db_table = 'route'


class Scenery(models.Model):
    scenery_id = models.IntegerField(primary_key=True)
    scenery_city = models.ForeignKey(City, models.DO_NOTHING, db_column='scenery_city')
    scenery_name = models.CharField(max_length=20)
    scenery_url = models.CharField(max_length=40)

    class Meta:
        managed = False
        db_table = 'scenery'


class User(models.Model):
    user_id = models.IntegerField(primary_key=True)
    user_name = models.CharField(max_length=20)
    user_pwd = models.CharField(max_length=40)

    class Meta:
        managed = True
        db_table = 'user'

tripRouting/views.py
import json

from django import forms
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from .models import User, City, Route


class UserForm(forms.Form):
    username = forms.CharField(label='username', max_length=50)
    password = forms.CharField(label='password', widget=forms.PasswordInput)


def index(request):
    """Load index page"""
    status = request.session.get('status', None)
    username = request.session.get('username', None)

    city_list = City.objects.all()

    if status == 1:
        return render(request, 'tripRouting/index.html',
                      {'islogin': True, 'username': username, 'city_list': city_list})
    return render(request, 'tripRouting/index.html', {'islogin': False, 'city_list': city_list})


def login(request):
    """Load login page"""
    if request.method == 'POST':
        userform = UserForm(request.POST)
        if userform.is_valid():
            username = userform.cleaned_data['username']
            password = userform.cleaned_data['password']
            user = User.objects.filter(user_name__exact=username, user_pwd__exact=password)
            if user:
                request.session['username'] = username
                request.session['status'] = 1
                request.session.set_expiry(0)
                return redirect('tripRouting:index')
            else:
                return render(request, 'tripRouting/login.html', {'userform': userform, 'msg': 'Invalid Login!'})
    else:
        userform = UserForm()
    return render(request, 'tripRouting/login.html', {'userform': userform, 'msg': None})


def logout(request):
    request.session.flush()
    return redirect('tripRouting:index')


def regist(request):
    if request.method == 'POST':
        userform = UserForm(request.POST)
        if userform.is_valid():
            username = userform.cleaned_data['username']
            password = userform.cleaned_data['password']
            userid = User.objects.latest('user_id').user_id + 1
            newuser = User(user_id=userid, user_name=username, user_pwd=password)
            newuser.save()
            return redirect('tripRouting:login')
    else:
        userform = UserForm()
    return render(request, 'tripRouting/regist.html', {'userform': userform})


def routing(request):
    status = request.session.get('status', None)
    if status != 1:
        return redirect('tripRouting:login')
    # Safety return
    return render(request, 'tripRouting/routing.html')


def routing_ajax_init(request):
    city_list = City.objects.all()
    route_list = Route.objects.all()
    cities = {}
    counter = 0
    for city in city_list:
        cities[counter] = str(city.to_json())
        counter += 1
    routes = {}
    counter = 0
    for route in route_list:
        routes[counter] = str(route.to_json())
        counter += 1
    return JsonResponse(json.dumps({'city': (json.dumps(cities, ensure_ascii=False).encode('utf-8').decode()),
                                    'route': json.dumps(routes, ensure_ascii=False).encode('utf-8').decode()},
                                   ensure_ascii=False).encode('utf-8').decode(), safe=False)


@csrf_exempt
def success(request):
    if request.method == 'POST':
        return render(request, 'tripRouting/success.html')
    else:
        context = json.loads(str(request.GET['data']))
        return render(request, 'tripRouting/success.html', context=context)

templates/tripRouting/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tripRouting/images/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tripRouting/styles/index.css' %}"/>
    <script src="{% static 'tripRouting/scripts/index.js' %}"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- jQuery and Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <title>欧洲之行，尽在掌握。欢迎来到EuroTrip</title>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" id="index-navbar">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tripRouting:index' %}" style="padding: 5px 25px 5px 15px">
                <img alt="Brand" src="{% static 'tripRouting/images/favicon.ico' %}"
                     style="height: 100%; width: inherit; padding: 0; margin: 0"/>
            </a>
            <b class="navbar-brand" style="padding-left: 0; font-size: 25px">EuroTrip</b>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'tripRouting:routing' %}">开始欧洲之旅<span
                        class="sr-only">(current)</span></a></li>
                <li><a href="#">了解欧洲</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">更多<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">查看欧洲城市</a></li>
                        <li><a href="#">查看交通方式</a></li>
                        <li><a href="#">景点一览</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">站点文档</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">关于我们</a></li>
                    </ul>
                </li>
            </ul>
            {% if islogin != True %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'tripRouting:login' %}">登录/注册</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">欢迎您：<b>{{ username }}</b> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">个人信息</a></li>
                            <li><a href="#">我的行程</a></li>
                            <li><a href="{% url 'tripRouting:logout' %}">退出登录</a></li>
                        </ul>
                    </li>
                </ul>
            {% endif %}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="page-header">
    <h1>欧洲之行，尽在掌握<br><small>欢迎来到EuroTrip！即刻开启你的行程！</small></h1><br>
    <div class="intro-button-area">
        {% if islogin != True %}
            <a href="{% url 'tripRouting:routing' %}">
                <button class="intro-button">即刻登录<span>！</span></button>
            </a>
        {% else %}
            <a href="{% url 'tripRouting:routing' %}">
                <button class="intro-button">开始行程<span>！</span></button>
            </a>
        {% endif %}
        <br><br><br></div>
</div>
<br>
<div class="city-show">
    {% for city in city_list %}
        <h4 class="city-label"><b>{{ city.city_name }}</b></h4>
        <img src="{% static 'tripRouting/images/'|add:city.city_url %}" alt="{{ city.city_name }}"
             class="city-show-img"/><br><br><br>
    {% endfor %}
</div>
</body>
</html>

templates/tripRouting/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tripRouting/images/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tripRouting/styles/login.css' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- jQuery and Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <title>登录到EuroTrip</title>
</head>
<body>

{% if msg %}
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">错误:</span>
        {{ msg }}
    </div>
{% endif %}
<div class="container">
    <div class="form-row">
        <form class="form-horizontal col-sm-offset-1 col-md-offset-1 login-form" method="post"
              enctype="multipart/form-data">{% csrf_token %}
            <h3 class="form-title">登录到EuroTrip</h3>
            <div class="form-group">
                <label for="username">用户名</label><br>
                {{ userform.username }}
            </div>
            <div class="form-group">
                <label for="password">密码</label><br>
                {{ userform.password }}
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="checkbox" onclick="check()">
                <label class="form-check-label" for="checkbox">我同意接受
                    <a href="#" title="最终用户许可协议" data-container="body" data-toggle="popover" data-placement="top"
                       data-content="信息系统开发与实践 小组成员：高世岷 陈澜 何泽海 成煜昊 导师：祝世伟">最终用户许可协议</a>
                </label>
            </div>
            <div class="form-group login-btn">
                <button type="submit" class="btn btn-primary" id="login" disabled="disabled">登录</button>
            </div>
            <div class="form-group login-btn">
                <a href="{% url 'tripRouting:regist' %}">
                    <button type="button" class="btn btn-info" id="regist">注册</button>
                </a>
            </div>
        </form>
    </div>
</div>
<script>
    function check() {
        var checkbox = document.getElementById("checkbox");
        if (checkbox.checked) {
            document.getElementById("login").disabled = "";
        } else {
            document.getElementById("login").disabled = "disabled";
        }
    }

    $(function () {
        $("[data-toggle='popover']").popover();
    });
</script>
</body>
</html>

templates/tripRouting/regist.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tripRouting/images/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tripRouting/styles/login.css' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- jQuery and Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <title>注册EuroTrip帐号</title>
</head>
<body>

{% if msg %}
    <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">错误:</span>
        {{ msg }}
    </div>
{% endif %}
<div style="" class="container">
    <div class="form-row">
        <form class="form-horizontal col-sm-offset-1 col-md-offset-1 login-form" method="post"
              enctype="multipart/form-data">{% csrf_token %}
            <h3 class="form-title">注册EuroTrip帐号</h3>
            <div class="form-group">
                <label for="username">用户名</label><br>
                {{ userform.username }}
            </div>
            <div class="form-group">
                <label for="password">密码</label><br>
                {{ userform.password }}
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="checkbox" onclick="check()">
                <label class="form-check-label" for="checkbox">我同意接受
                    <a href="#" title="最终用户许可协议" data-container="body" data-toggle="popover" data-placement="top"
                       data-content="信息系统开发与实践 小组成员：高世岷 陈澜 何泽海 成煜昊 导师：祝世伟">最终用户许可协议</a>
                </label>
            </div>
            <div class="form-group login-btn">
                <button type="submit" class="btn btn-primary" id="regist" disabled="disabled">注册</button>
            </div>
        </form>
    </div>
</div>
<script>
    function check() {
        var checkbox = document.getElementById("checkbox");
        if (checkbox.checked) {
            document.getElementById("regist").disabled = "";
        } else {
            document.getElementById("regist").disabled = "disabled";
        }
    }

    $(function () {
        $("[data-toggle='popover']").popover();
    });
</script>
</body>
</html>

templates/tripRouting/routing.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tripRouting/images/favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'tripRouting/styles/routing.css' %}"/>
    <!-- jQuery and Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'tripRouting/scripts/routing.js' %}"></script>
    <!-- Baidu Map -->
    <script type="text/javascript"
            src="https://api.map.baidu.com/api?v=1.0&&type=webgl&ak=lpMMxyYU12aBGREnihgEIZzMjfo5TUY2"></script>
    <script type="text/javascript" src="{% static 'tripRouting/scripts/map.js' %}"></script>
    <title>Routing</title>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" id="routing-navbar">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tripRouting:index' %}" style="padding: 5px 25px 5px 15px">
                <img alt="Brand" src="{% static 'tripRouting/images/favicon.ico' %}"
                     style="height: 100%; width: inherit; padding: 0; margin: 0"/>
            </a>
            <b class="navbar-brand" style="padding-left: 0; font-size: 25px">EuroTrip</b>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'tripRouting:index' %}">回到主页</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="number" class="form-control" id="trip-budget" placeholder="预算">
                </div>
                <div class="form-group">
                    <input type="number" class="form-control" id="trip-days" placeholder="天数">
                </div>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!-- 提示 -->
<div class='alert alert-heading' hidden>
    <a href='#' class='close' data-dismiss='alert'><span>×</span></a>
    <h4 id="notice-title"></h4>
    <h6 id="notice-text"></h6>
</div>

<!-- 路径选择弹窗部分 -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">请选择交通方式</h4>
            </div>
            <div class="modal-body">
                <div class="form-group" id="modal_route_list">
                </div>
            </div>
        </div>
    </div>
</div>


<!-- 选择条件部分 -->
<div id="container"></div>
<!--
<div class="input-area">
    <label for="trip-days">Your days</label>
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon3">Suppose: </span>
        <input type="text" class="form-control" id="trip-days" aria-describedby="basic-addon3">
        <span class="input-group-addon">days</span>
    </div>
    <label for="trip-budget">Your budget</label>
    <div class="input-group">
        <span class="input-group-addon">$</span>
        <input type="text" class="form-control" id="trip-budget" aria-describedby="basic-addon3">
        <span class="input-group-addon">.00</span>
    </div>
</div>
-->

<div class="main-area" id="main-function" hidden>
    <!-- 向js传递限制信息 保持hidden -->
    <div class="constraint-info" id="city-list" hidden>
        <label for="days-info">Days: </label><input type="text" id="days-info" value=""/>
        <label for="budget-info">Budgets:</label><input type="text" id="budget-info" value=""/>
    </div>
    <!-- 城市选项部分 -->
    <div class="city-area"></div>
    <br><input type="button" class="btn btn-primary con-btn" id="continue" value="选择完毕"
               onclick="submit(user_selection);">
</div>

<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="info-container">
        <h5 id="bottom-info">信息系统开发与实践 小组成员：高世岷 陈澜 何泽海 成煜昊 导师：祝世伟</h5>
    </div>
</nav>
</body>
</html>

templates/tripRouting/success.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tripRouting/images/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'tripRouting/styles/success.css' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- jQuery and Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'tripRouting/scripts/success.js' %}"></script>
    <title>查看行程</title>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" id="index-navbar">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tripRouting:index' %}" style="padding: 5px 25px 5px 15px">
                <img alt="Brand" src="{% static 'tripRouting/images/favicon.ico' %}"
                     style="height: 100%; width: inherit; padding: 0; margin: 0"/>
            </a>
            <b class="navbar-brand" style="padding-left: 0; font-size: 25px">EuroTrip</b>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'tripRouting:routing' %}">Start your EuroTrip! <span
                        class="sr-only">(current)</span></a></li>
                <li><a href="#">Learn about European</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">More <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Check Citys</a></li>
                        <li><a href="#">Check Routes</a></li>
                        <li><a href="#">Check Sceneries</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Website docs</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">About Us</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="page-header">
    <h1>您的行程信息如下<br></h1>
</div>
<div id="result-show">
    <h3 id="result-head">行程创建时间：<small id="time"></small></h3>
    <h3 id="result-foot">行程金额与时间：</h3>
</div>
<div id="button-group">
    <a href="{% url 'tripRouting:routing' %}">
        <input type="button" class="btn btn-primary btn-default" value="重新规划行程">
    </a>
    <a href="{% url 'tripRouting:index' %}">
        <input type="button" class="btn btn-primary btn-info" value="返回主页">
    </a>
</div>
</body>
</html>